apiVersion: v1
kind: Service 
metadata:
  name: clientes-svc
  namespace: default
  labels:
    app: clientes
    service: clientes
spec:
  ports: 
  - port: 5000
    name: http
  selector:
    app: clientes
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: clientes-v1
  namespace: default
  labels:
    app: clientes
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: clientes
  template:
    metadata: 
      labels:
        app: clientes
        version: v1
    spec:
      containers:
        - name: clientes
          image: rxcore/clientes:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          env:
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: db-mongoatlas-secret
                  key: dbUser
            - name: "DB_PASS"
              valueFrom:
                secretKeyRef:
                  name: db-mongoatlas-secret
                  key: dbPass
            - name: "CLUSTER"
              valueFrom:
                secretKeyRef:
                  name: db-mongoatlas-secret
                  key: cluster
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 4000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 4000
              scheme: HTTP
            initialDelaySeconds: 50
            timeoutSeconds: 10
            failureThreshold: 10
